version: '3'

services:
  users:
    build: ./users
    image: users:latest
    container_name: users
    command: python CC_0125_0172_0242_1557_ride_share_users.py
    restart: always
    ports:
      - "8080:80"
    environment:
      - TEAM_NAME=CC_0125_0172_0242_1557
    volumes:
      - ./users:/users
      
  rides:
    build: ./rides
    image: rides:latest
    container_name: rides
    command: python CC_0125_0172_0242_1557_ride_share_rides.py
    restart: always
    ports: 
      - "8000:80"
    environment:
      - TEAM_NAME=CC_0125_0172_0242_1557
    volumes:
      - ./rides:/rides
  
